

services:
  geth:
    image: ethereum/client-go:stable
    container_name: ethereum
    command:
      - --mainnet
      - --datadir=/opt/ethereumd/.ethereum
      - --ws
      - --http
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/opt/ethereumd/.ethereum/jwt.hex
    ports:
      - 8545:8545
      - 30303:30303
    volumes:
      - ./ethdata:/opt/ethereumd/.ethereum
      - ./jwt.hex:/opt/ethereumd/.ethereum/jwt.hex

  beacon:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
    container_name: beacon
    command:
      - --mainnet
      - --config-file=/opt/ethereumd/data/beacon.yaml
      - --checkpoint-sync-url=${CHECKPOINT_URL}
      - --genesis-beacon-api-url=${CHECKPOINT_URL}
    ports:
      - 3500:3500
      - 12000:12000
    volumes:
      - ./ethdata:/opt/ethereumd/data
      - ./beacon.yaml:/opt/ethereumd/data/beacon.yaml
      - ./jwt.hex:/opt/ethereumd/data/jwt.hex
