services:
  evm-verifier:
    image: flarefoundation/evm-verifier
    container_name: evm-verifier
    restart: unless-stopped
    ports:
      - 9800:9800
    environment:
      PORT: 9800
      API_KEYS: apikey
      RPC_FLR: "http://flare-node:9650/ext/bc/C/rpc"
      RPC_ETH: "http://ethereum-node:8545/"
      APP_BASE_PATH: "/verifier"
      TESTNET: false

