

services:
  indexer:
    image: flarefoundation/attestation-client
    volumes:
      - ../credentials.prepared/xrp-indexer-verifier:/app/attestation-suite-config
    container_name: indexer-xrp-indexer
    command: indexer xrp
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test123
      TESTNET: ${TESTNET}
    depends_on:
      - database

  verification-server:
    image: flarefoundation/attestation-client
    volumes:
      - ../credentials.prepared/xrp-indexer-verifier:/app/attestation-suite-config
    container_name: indexer-xrp-verification-server
    command: verification-server
    restart: unless-stopped
    environment:
      VERIFIER_TYPE: xrp
      APP_BASE_PATH: /verifier/xrp
      MYSQL_ROOT_PASSWORD: test123
      TESTNET: ${TESTNET}
    depends_on:
      - database
    ports:
      - 9501:9500

  database:
    image: mysql:8-debian
    container_name: indexer-xrp-database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test123
    cap_add:
      - SYS_NICE
    ports:
      - 127.0.0.1:23306:3306
    volumes:
    #   - ./mysql-conf.d/:/etc/mysql/conf.d
    #   - ./mysql-initdb/:/docker-entrypoint-initdb.d
      - indexer-xrp-db:/var/lib/mysql

  spammer:
    image: flarefoundation/attestation-client
    profiles: ["spammer"]
    volumes:
      - ../credentials.prepared/xrp-indexer-verifier:/app/attestation-suite-config
    container_name: indexer-xrp-spammer
    command: spammer XRP 10000
    restart: unless-stopped
    environment:
      TESTNET: ${TESTNET}

volumes:
  indexer-xrp-db:
